### ISSUE TITLE
改善点

### ISSUE THREAD

**Issue by YoungmanCH** [mongesan/Dart-base#1]
5行目〜6行目は、グローバル変数になっているので、変数を管理するためのクラスを作成しよう！

void main() {}関数以外の関数は、グローバル関数になっているので、関数を管理するためのクラスを作成しよう！

12行目のcount()関数内の19行目〜27行目の処理は、toStirng()で文字列化している処理と +1をする処理、という二つの処理が混ざっているので、分割して管理しよう！（関数に単一責任を持たせると呼びます。）

43行目以下の getstdin()関数では、  print()処理と timeSave = 0;の初期化処理、　timeMovinng = falseの真偽値処理が複数に分けられて行われています。 getstdin()関数内で行うには名前が不適切です。上記と同様に分割処理を行おう！

**Comment by mongesan** [comment]
春学期があまりに忙しく、折角貴重なご指摘を頂いていたのにまったく手を付けられていませんでした...すみません。夏休みに入って時間が出来たので、改善点を元に書きなおしを行いました。Refactoringブランチおよび、Pull Request #2 に修正したものを上げましたので、お時間があれば見て頂けると幸いです。

**Comment by YoungmanCH** [comment]
Nice job!!

確認しました。

ストレートに話すと、関数毎に機能を分割して管理できているので、全体的に少し良くなっています。しかし、このストップウォッチを他者が改善、運用するには以下の点にて不便となっています。


・コードは、実行される順番にそって記述する。
コードは、上から順に実行されるため、関数の記述位置は、再度整理しましょう。あっち行ったりこっち行ったりみたいな状態なので、改善するだけでとても綺麗に見えます。

・命名規則を理解する
lineOperation、time_to_mmss　などは、関数名として不適切です。関数名は、動詞+名詞　にしましょう。クラス名は名詞のみで表現するのが適切です。

・Timerクラスが大きすぎる
現在のTimerクラスは、start, stop, resetというストップウォッチ機能に加えて、メッセージを表示する機能、カウントする機能、キーボードの入力値を識別する機能など、機能が多すぎます。なので、他のクラスを用意して一つ一つのクラスの機能を小さくしましょう。

クラスが小さくなることで、よりコードが明確になり運用、アップデートが容易になりやすくなるでしょう。



これらのアドバイスをもとにプログラミングをすることで、プログラミング初心者を脱却できると思います！
あと少し！Fight!!

**Comment by mongesan** [comment]
お忙しい中どうもありがとうございます。
改善点確認しました。
オブジェクト指向に慣れていないので、機能・クラスの分け方にかなり苦心している所です。
時間出来次第、実装方法考えて書き直します。

**Comment by mongesan** [comment]
書き直してみました。
・元のTimerクラスを、コンソールの入出力機能を担当するTimerUIクラスと、数え上げを担当するTimerクラスの二つに分けてみました。いかがでしょうか。
・関数の位置を変えてみましたが、これで多少見やすくなりましたでしょうか。
・クラス・関数の命名規則に問題はありませんか。
お忙しいところすみません。

**Comment by YoungmanCH** [comment]
確認しました。

出来栄えとしては、素晴らしいです！

自分自身で改めてコードを見ても一目瞭然の出来栄えのように感じると思います。

これで、次のステップに進んで頂いてOKです！

これからは、プログラムを書くときに今回みたく、関数名、単一責任化等を意識してClean Codeを徹底してみましょう！

お疲れ様でした
